#!/usr/bin/env python

'''Constant list of all AWE API functions.'''

AWE_FUNCTIONS = [
            'accesskeys',
            'aria-allowed-attr',
            'aria-required-attr',
            'aria-required-children',
            'aria-required-parent',
            'aria-roles',
            'aria-valid-attr-value',
            'aria-valid-attr',
            'audio-caption',
            'button-name',
            'bypass',
            'color-contrast',
            'definition-list',
            'dlitem',
            'document-title',
            'duplicate-id',
            'frame-title',
            'html-lang',
            'html-lang-valid',
            'Output',
            'image-alt',
            'input-image-alt',
            'label',
            'layout-table',
            'link-name',
            'list',
            'list-item',
            'meta-refresh',
            'meta-viewport',
            'object-alt',
            'tab-index',
            'td-headers-attr',
            'th-data-cells:',
            'valid-lang',
            'video-caption',
            'video-description'
        ]
